# Generated by Django 5.2.8 on 2025-12-01 13:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('color', models.CharField(default='secondary', max_length=20, verbose_name='Цвет Bootstrap')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Статус бронирования',
                'verbose_name_plural': 'Статусы бронирований',
                'db_table': 'booking_statuses',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PricingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Код периода')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('hours_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество часов')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Период аренды',
                'verbose_name_plural': 'Периоды аренды',
                'db_table': 'pricing_periods',
                'ordering': ['sort_order', 'hours_count'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название региона')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'db_table': 'regions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-имя')),
                ('icon', models.CharField(default='fa-building', max_length=50, verbose_name='Иконка FontAwesome')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория помещения',
                'verbose_name_plural': 'Категории помещений',
                'db_table': 'space_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус транзакции',
                'verbose_name_plural': 'Статусы транзакций',
                'db_table': 'transaction_statuses',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('client', 'Клиент'), ('owner', 'Владелец'), ('admin', 'Администратор')], default='client', max_length=10, verbose_name='Тип пользователя')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Компания')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email подтвержден')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='rental.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'cities',
                'ordering': ['name'],
                'unique_together': {('name', 'region')},
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название помещения')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-имя')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('area_sqm', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Площадь (м²)')),
                ('max_capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Макс. вместимость')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемое')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spaces', to='rental.city', verbose_name='Город')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_spaces', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spaces', to='rental.spacecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
                'db_table': 'spaces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Начало аренды')),
                ('end_datetime', models.DateTimeField(verbose_name='Окончание аренды')),
                ('periods_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество периодов')),
                ('price_per_period', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за период')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общая стоимость')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Арендатор')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental.bookingstatus', verbose_name='Статус')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental.pricingperiod', verbose_name='Период аренды')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rental.space', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='spaces/%Y/%m/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt текст')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rental.space', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Фото помещения',
                'verbose_name_plural': 'Фото помещений',
                'db_table': 'space_images',
                'ordering': ['-is_primary', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Способ оплаты')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='Внешний ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата транзакции')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='rental.booking', verbose_name='Бронирование')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental.transactionstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('social_vk', models.URLField(blank=True, verbose_name='ВКонтакте')),
                ('social_telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='rental.booking', verbose_name='Бронирование')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rental.space', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'unique_together': {('space', 'author')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='rental.space', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'db_table': 'favorites',
                'unique_together': {('user', 'space')},
            },
        ),
        migrations.CreateModel(
            name='SpacePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('min_periods', models.PositiveIntegerField(default=1, verbose_name='Мин. периодов')),
                ('max_periods', models.PositiveIntegerField(default=100, verbose_name='Макс. периодов')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='space_prices', to='rental.pricingperiod', verbose_name='Период')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='rental.space', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Цена помещения',
                'verbose_name_plural': 'Цены помещений',
                'db_table': 'space_prices',
                'ordering': ['period__sort_order'],
                'unique_together': {('space', 'period')},
            },
        ),
    ]
