# Generated by Django 6.0 on 2025-12-05 12:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Создание'), ('update', 'Редактирование'), ('delete', 'Удаление'), ('view', 'Просмотр'), ('login', 'Вход'), ('logout', 'Выход'), ('other', 'Другое')], db_index=True, max_length=20, verbose_name='Тип действия')),
                ('model_name', models.CharField(db_index=True, max_length=100, verbose_name='Модель')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('object_repr', models.CharField(max_length=255, verbose_name='Представление объекта')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Изменения')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата действия')),
            ],
            options={
                'verbose_name': 'Журнал действий',
                'verbose_name_plural': 'Журнал действий',
                'db_table': 'action_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_datetime',
            field=models.DateTimeField(db_index=True, verbose_name='Окончание аренды'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_datetime',
            field=models.DateTimeField(db_index=True, verbose_name='Начало аренды'),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название города'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('client', 'Клиент'), ('owner', 'Владелец'), ('admin', 'Администратор')], db_index=True, default='client', max_length=10, verbose_name='Тип пользователя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Одобрен'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='space',
            name='area_sqm',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Площадь (м²)'),
        ),
        migrations.AlterField(
            model_name='space',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='space',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='space',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Рекомендуемое'),
        ),
        migrations.AlterField(
            model_name='spacecategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='spaceimage',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='spaceprice',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='spaceprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата транзакции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Внешний ID'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tenant', 'status'], name='idx_booking_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['space', 'start_datetime'], name='idx_booking_space_start'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='idx_booking_period'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['is_active', 'name'], name='idx_city_active_name'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='idx_user_email'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_type', 'is_active'], name='idx_user_type_active'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'created_at'], name='idx_favorite_user'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['space', 'is_approved'], name='idx_review_space_approved'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['author', 'created_at'], name='idx_review_author'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['is_active', 'is_featured'], name='idx_space_active_featured'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['city', 'is_active'], name='idx_space_city_active'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['category', 'is_active'], name='idx_space_category_active'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['-views_count'], name='idx_space_views'),
        ),
        migrations.AddIndex(
            model_name='spaceimage',
            index=models.Index(fields=['space', 'is_primary'], name='idx_image_space_primary'),
        ),
        migrations.AddIndex(
            model_name='spaceprice',
            index=models.Index(fields=['space', 'is_active'], name='idx_price_space_active'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['booking', 'status'], name='idx_transaction_booking'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['user', 'action_type'], name='idx_log_user_action'),
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['model_name', 'object_id'], name='idx_log_model_object'),
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['created_at', 'action_type'], name='idx_log_date_action'),
        ),
    ]
